services:
    efcore-api:
        build:
            context: .
            dockerfile: EFCoreCourse/Docker/Dockerfile
            
        image: efcorecourse-api
        ports:
            -  "8080:8080"
        
        env_file:
            - .env